name: Integrity Check

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup NodeJS with Yarn Caching
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: Install NodeJS Dependencies
      run: yarn install
    
    - name: Build Express Service
      run: yarn build:service

    - name: Deploy Express Service to Azure
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'amnis-express-devop'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AMNIS_EXPRESS_DEVOP_PUBLISH_PROFILE }}
        package: ./packages/amnis-express/.srv

  build:
    runs-on: ubuntu-latest
    needs: deploy

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup NodeJS with Yarn Caching
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
    
    - name: Install NodeJS Dependencies
      run: yarn install

    - name: Lint for Code-Style Errors
      run: yarn lint

    - name: Run Core Unit Tests
      run: yarn test:core

    - name: Run Database Unit Tests
      run: yarn test:db

    - name: Run API Unit Tests
      run: yarn test:api

    - name: Run State Unit Tests
      run: yarn test:state

    - name: Run Build
      run: yarn build