name: Integrity Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Apt
      run: sudo apt-get update

    - name: Install ffmpeg
      run: sudo apt install ffmpeg

    - name: Setup NodeJS with Yarn Caching
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    
    - name: Install NodeJS Dependencies
      run: yarn install

    - name: Lint for Code-Style Errors
      run: yarn lint

    - name: Run Unit Tests
      run: yarn test

    - name: Run Build
      run: yarn build